<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginBtn</name>
   <tag></tag>
   <elementGuidId>e299c4c3-e474-4705-be68-64cf3dab7cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec53b675-a526-40ff-8149-5decf84de425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ff235ce-b93a-4c9e-9fee-c24974a6f60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>outline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a503fb46-8873-4584-8aae-b8cb1ec8c82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontweight</name>
      <type>Main</type>
      <value>semibold</value>
      <webElementGuid>96450969-d0bf-4a0a-8417-36cc3454effc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!py-1.5 md:!py-[10px] !px-3 md:!px-6 button outline semibold</value>
      <webElementGuid>bfc5330f-e092-4c30-bb02-7d14aeac485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Login
    </value>
      <webElementGuid>531ee163-6350-4b7e-acf9-c5a2af1c9caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;sticky w-full top-0 z-[12] bg-black p-2&quot;]/div[@class=&quot;flex justify-between items-center p-4 bg-normal-700 rounded-[10px] border border-normal-500 gap-8&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;flex items-center&quot;]/a[1]/button[@class=&quot;!py-1.5 md:!py-[10px] !px-3 md:!px-6 button outline semibold&quot;]</value>
      <webElementGuid>cf28b3a7-18e9-45f7-9e78-cc86799f430d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>9017dcc3-234a-47a3-b572-1bef85105c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div/div/div[2]/div/a/button</value>
      <webElementGuid>97eb43ed-73cd-4823-ad58-d28af1d31fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join'])[1]/preceding::button[1]</value>
      <webElementGuid>f4da2ffc-9452-42e8-a725-6b4d57f76934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipslip'])[1]/preceding::button[2]</value>
      <webElementGuid>6d7cf36f-8d2d-4e45-956a-80226c669426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>d8fcb8d2-37b8-49dd-912f-6690fdc1328f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ef7b7dd4-b144-4169-894f-edbe2148c37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
      Login
    ' or . = '
      Login
    ')]</value>
      <webElementGuid>be7a0f8d-4859-4c74-a9d1-0649b2086298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
