<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>deleteConfirmationBtn</name>
   <tag></tag>
   <elementGuidId>f7eff719-ccd9-4da8-b6ac-f4f37eed3897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>77f0bbda-7400-4cb5-b143-ff7cbaa463a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9756fb3d-cc02-463e-b35f-50ae9b3eca4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontweight</name>
      <type>Main</type>
      <value>semibold</value>
      <webElementGuid>cf7ec827-f1a3-45f4-8e79-ab788fa26adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-1.5 !py-2.5 !px-[50px] min-w-[150px] button semibold</value>
      <webElementGuid>a99446de-c7f3-4470-b69c-5d46e9f5610a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Delete
    </value>
      <webElementGuid>005879e8-86e2-4cd2-b28c-652bdb5830b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;home-page&quot;]/div[@class=&quot;feed-layout&quot;]/div[@class=&quot;max-h-full overflow-auto space-y-4 py-4 pt-8&quot;]/div[@class=&quot;bg-normal-850 rounded-lg flex justify-center gap-4 w-full&quot;]/div[@class=&quot;flex flex-col w-full gap-4 p-4 cursor-pointer&quot;]/div[@class=&quot;md:max-w-[600px] w-full mx-auto&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal !bg-normal-600 !rounded-lg&quot;]/div[@class=&quot;flex items-center justify-center mb-8&quot;]/button[@class=&quot;ml-1.5 !py-2.5 !px-[50px] min-w-[150px] button semibold&quot;]</value>
      <webElementGuid>0c70c25e-7265-4b38-a0fd-73721cb29d2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>5b6b0323-07e0-4256-8361-3a980946b47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>e4f30662-5eb8-4388-a37e-2bfa1c261be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>24afd793-50d2-4ddb-a036-d982af11465a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Howl'])[1]/following::button[2]</value>
      <webElementGuid>444f8839-2e97-49dc-b640-f3b138265dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your browser does not support HTML video.'])[1]/preceding::button[1]</value>
      <webElementGuid>961fa6cc-99b4-4396-ac16-05b696f23421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::button[1]</value>
      <webElementGuid>65ee953a-45fe-40f2-8900-25d9d8797a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>acfb11fd-3871-45b6-a8a8-8f13702e37fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
      Delete
    ' or . = '
      Delete
    ')]</value>
      <webElementGuid>d783106c-d8ba-4801-b57d-917e4f49e155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
