<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>displayNameTxt</name>
   <tag></tag>
   <elementGuidId>fa6159c7-38e3-4983-91d9-284970f4fa84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;nguyenqhuy7531&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa38ef36-2df2-46c2-85f4-4060111fe5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate hover:underline typography_LUXcC variant-surtitle_NSeey font-weight-semibold_08cRQ</value>
      <webElementGuid>e444c8d4-48ad-44d3-9c0a-7564161ee249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  nguyenqhuy7531
                </value>
      <webElementGuid>79d490f0-46d8-4144-ba99-cf3c114de649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;home-page&quot;]/div[@class=&quot;feed-layout&quot;]/div[@class=&quot;max-h-full overflow-auto space-y-4 py-4 pt-8&quot;]/div[@class=&quot;bg-normal-850 rounded-lg flex justify-center gap-4 w-full&quot;]/div[@class=&quot;flex flex-col w-full gap-4 p-4 cursor-pointer&quot;]/div[@class=&quot;md:max-w-[600px] w-full mx-auto&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/div[@class=&quot;flex justify-start gap-4&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;max-w-[250px]&quot;]/div[@class=&quot;flex items-center gap-1&quot;]/div[1]/div[@class=&quot;truncate hover:underline typography_LUXcC variant-surtitle_NSeey font-weight-semibold_08cRQ&quot;]</value>
      <webElementGuid>cd6384e1-157f-49f5-8b6e-a2927b693099</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>23a24b92-016a-44ab-9f53-3b31e90b787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::div[13]</value>
      <webElementGuid>62cf6fd4-9e19-40a9-99f4-c31d7a611122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All punters'])[1]/following::div[13]</value>
      <webElementGuid>bc94028e-0b06-4ee8-90a8-ca22e19fccc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@nguyenqhuy753101'])[1]/preceding::div[1]</value>
      <webElementGuid>a8c3edc4-60fd-4256-a01c-2018e6977bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[4]</value>
      <webElementGuid>db34168d-588f-44ee-b0a5-077efbcfba3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nguyenqhuy7531']/parent::*</value>
      <webElementGuid>05c21d1a-b4fc-4252-a67e-6725f5f450f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>7f69a42b-e625-49c4-97d6-59660cd40a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                  nguyenqhuy7531
                ' or . = '
                  nguyenqhuy7531
                ')]</value>
      <webElementGuid>31b2f912-b7e8-495e-962d-93a182876b63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
