<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadedImage</name>
   <tag></tag>
   <elementGuidId>02cf4f7e-319a-4ccf-bad4-41b8ee73842b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div[2]/div/div/div/div/figure/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.max-h-full.max-w-full.w-full.h-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=figure >> img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a75f534c-14c5-4229-a75c-6f135a28e4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-dev.wolfden.bet/assets/users/283c1d1a-3254-4a0e-997c-92eff9f28bc8/tweets/image_6b47de91d66a4325ad97572903de2f31.png</value>
      <webElementGuid>ea5c621e-921b-47ff-9ea1-6efff5530a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-h-full max-w-full w-full h-full</value>
      <webElementGuid>0af7cf2d-3b5b-42e1-804d-e551227f1ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;home-page&quot;]/div[@class=&quot;feed-layout&quot;]/div[@class=&quot;max-h-full overflow-auto space-y-4 py-4 pt-8&quot;]/div[@class=&quot;bg-normal-850 rounded-lg flex justify-center gap-4 w-full&quot;]/div[@class=&quot;flex flex-col w-full gap-4 p-4 cursor-pointer&quot;]/div[@class=&quot;md:max-w-[600px] w-full mx-auto&quot;]/div[2]/div[1]/div[@class=&quot;grid gap-3 my-3&quot;]/div[@class=&quot;w-full relative&quot;]/div[@class=&quot;rounded-xl overflow-hidden container gap-0.5 one&quot;]/figure[@class=&quot;flex justify-center items-center h-full overflow-hidden cursor-pointer media-1&quot;]/img[@class=&quot;max-h-full max-w-full w-full h-full&quot;]</value>
      <webElementGuid>9f084141-8505-4c4a-988b-6ea06cda1a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div[2]/div/div/div/div/figure/img</value>
      <webElementGuid>05a3173c-c176-46a1-a3e2-4c68c322039d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-dev.wolfden.bet/assets/users/283c1d1a-3254-4a0e-997c-92eff9f28bc8/tweets/image_6b47de91d66a4325ad97572903de2f31.png')]</value>
      <webElementGuid>cf97c785-31f2-496b-a157-83089ad35ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>7f41da80-b4f4-473d-ad90-ac4fad92bf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-dev.wolfden.bet/assets/users/283c1d1a-3254-4a0e-997c-92eff9f28bc8/tweets/image_6b47de91d66a4325ad97572903de2f31.png']</value>
      <webElementGuid>a64f744c-e389-48a5-aa7c-d14bb6538ccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
