<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameTxt</name>
   <tag></tag>
   <elementGuidId>97d4ce16-75d1-4d85-bde6-d354607164c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;@nguyenqhuy753101&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc3ac720-ca45-43a9-9321-4f1893db1788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-name text-normal-300 max-w-[250px] truncate typography_LUXcC variant-surtitle_NSeey font-weight-normal_aKbW-</value>
      <webElementGuid>05c47c39-6759-4ae0-8182-9ff377d83178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                @nguyenqhuy753101
              </value>
      <webElementGuid>d46395ea-915a-4ea0-b6b2-61a1d869e966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;home-page&quot;]/div[@class=&quot;feed-layout&quot;]/div[@class=&quot;max-h-full overflow-auto space-y-4 py-4 pt-8&quot;]/div[@class=&quot;bg-normal-850 rounded-lg flex justify-center gap-4 w-full&quot;]/div[@class=&quot;flex flex-col w-full gap-4 p-4 cursor-pointer&quot;]/div[@class=&quot;md:max-w-[600px] w-full mx-auto&quot;]/div[@class=&quot;flex justify-between items-center&quot;]/div[@class=&quot;flex justify-start gap-4&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;max-w-[250px]&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/div[@class=&quot;user-name text-normal-300 max-w-[250px] truncate typography_LUXcC variant-surtitle_NSeey font-weight-normal_aKbW-&quot;]</value>
      <webElementGuid>56d00494-317b-4921-a267-ff67ff175df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/div/div[2]/div/div/div/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>4b26b755-4707-43f1-b620-12b5d4b21507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nguyenqhuy7531'])[1]/following::div[2]</value>
      <webElementGuid>d0306c21-2b19-4e5e-beda-b424925c7eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::div[15]</value>
      <webElementGuid>8728baa8-3b10-4b25-a682-0031512ac1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[2]</value>
      <webElementGuid>d54071c3-cab6-4ebc-a810-30f7ed4f620b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::div[13]</value>
      <webElementGuid>a360ef76-507f-4466-93cd-921f22d41696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='@nguyenqhuy753101']/parent::*</value>
      <webElementGuid>7ac494ed-f5a1-4297-96ab-a03d48603ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>5246e69e-00a9-4020-8107-903f7aa65d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                @nguyenqhuy753101
              ' or . = '
                @nguyenqhuy753101
              ')]</value>
      <webElementGuid>be3796d0-e3f1-45ff-a24e-b166c0b4e9dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
