<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>howlBtn</name>
   <tag></tag>
   <elementGuidId>e2773cf5-bceb-4df8-bd69-ffacaa1fbd85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[1877]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Howl&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58d09b90-ddb1-427c-a7b0-d1cdc89e7163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c7434d5-3dd6-46fa-85da-464a0d8b89db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontweight</name>
      <type>Main</type>
      <value>regular</value>
      <webElementGuid>c82268a2-a5b2-4800-af8d-fd4db81c5deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lg:text-lg !font-semibold !rounded-xl button regular</value>
      <webElementGuid>7ab2547c-c4de-4b4d-8c68-a491313bdc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Howl
    </value>
      <webElementGuid>221f2ebb-985e-4757-b350-baf63980ae2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;vm--container scrollable&quot;]/div[@class=&quot;vm--modal !bg-dark-550 !rounded-xl !max-h-[90vh]&quot;]/div[@class=&quot;flex justify-end items-center p-4&quot;]/button[@class=&quot;lg:text-lg !font-semibold !rounded-xl button regular&quot;]</value>
      <webElementGuid>e3a0eb88-7a2f-4bcf-b382-d8661cb788bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[1877]</value>
      <webElementGuid>e2da2616-8792-4d2d-96e4-1556c422140b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[4]/div[2]/div[3]/button</value>
      <webElementGuid>4e6114a0-63cb-4d97-9469-56d63157a617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or drag and drop'])[1]/following::button[2]</value>
      <webElementGuid>044d8d25-3d51-495a-8b2f-07f18131077b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flags'])[1]/following::button[270]</value>
      <webElementGuid>a76239e0-6cbb-4582-bf97-298a8f0a0ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Howl']/parent::*</value>
      <webElementGuid>1d311cf1-3009-4a89-b736-04dfebd9bdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>7b22bb90-9358-444d-b991-c966e496f519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
      Howl
    ' or . = '
      Howl
    ')]</value>
      <webElementGuid>b157e408-eea6-4910-8aa5-76394ba0ad0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
