<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>displayNameTxt</name>
   <tag></tag>
   <elementGuidId>10ec525c-1afd-4c68-8664-474b2a96c491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wolfden']/div[2]/div[2]/main/main/div/div/div/div[2]/div/div[2]/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;nguyenqhuy7531&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9e5df3d4-f331-482b-8c7b-8352564cba3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!text-base md:!text-xl break-all !text-primary-300 typography_LUXcC variant-title_K7y2D font-weight-bold_ltkpC</value>
      <webElementGuid>9462c3e9-16c9-4546-a535-b245f52f254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            nguyenqhuy7531
          </value>
      <webElementGuid>fb612dbf-3d6c-4c12-8696-a89722f5aa6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;saved-feed&quot;]/main[@class=&quot;justify-center items-center&quot;]/div[@class=&quot;flex flex-col justify-center relative&quot;]/div[@class=&quot;max-w-full max-h-full&quot;]/div[@class=&quot;relative h-[300px] max-w-full max-h-full overflow-auto&quot;]/div[@class=&quot;absolute left-0 bottom-0 right-0 p-2 md:p-6&quot;]/div[1]/div[@class=&quot;md:mt-4 grid gap-2 md:gap-4 items-end md:items-center grid-cols-1 md:grid-cols-[1fr_2fr_1fr]&quot;]/div[@class=&quot;relative md:w-full md:h-full flex items-center p-2 rounded-[10px] overflow-hidden&quot;]/div[@class=&quot;relative h-full flex items-center justify-between gap-4&quot;]/div[@class=&quot;flex-1&quot;]/p[@class=&quot;!text-base md:!text-xl break-all !text-primary-300 typography_LUXcC variant-title_K7y2D font-weight-bold_ltkpC&quot;]</value>
      <webElementGuid>23392e51-e434-4351-9f2d-7e4bc6b80ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/main/div/div/div/div[2]/div/div[2]/div/div[2]/div/p</value>
      <webElementGuid>efe493dc-ca69-4619-8cad-7fd54bf07308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/following::p[13]</value>
      <webElementGuid>01e24149-da17-413a-afd8-24db5c5284f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::p[14]</value>
      <webElementGuid>db078a18-1028-436d-a2bc-2fa3085a57b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/preceding::p[7]</value>
      <webElementGuid>e439d76f-97d5-48d3-814c-906de7c13ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Howls'])[1]/preceding::p[7]</value>
      <webElementGuid>a78765e2-1b76-4eb2-9f7d-42b5e809b537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nguyenqhuy7531']/parent::*</value>
      <webElementGuid>aa20382b-9c55-4d4e-a48a-b8590d9bfef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/p</value>
      <webElementGuid>f78dfe77-7d39-46cc-8b53-ce3644ee5cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
            nguyenqhuy7531
          ' or . = '
            nguyenqhuy7531
          ')]</value>
      <webElementGuid>e1880a81-b210-4646-8af0-b37c623ebad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
