<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameTxt</name>
   <tag></tag>
   <elementGuidId>6f6019ec-5e05-448d-a3b4-f607fd1e569e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wolfden']/div[2]/div[2]/main/main/div/div/div/div[2]/div/div[2]/div/div[2]/div/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;@nguyenqhuy753101&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8ac7a4dd-b9ec-458e-902f-387303a8b465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!text-sm md:!text-base break-all !text-white/70 typography_LUXcC variant-subtitle_+fl6g font-weight-normal_aKbW-</value>
      <webElementGuid>97bd04ba-81c6-4657-bbca-b725be83a482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            @nguyenqhuy753101
          </value>
      <webElementGuid>e1eacbd0-000c-47bd-a363-3dffb5508546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wolfden&quot;)/div[@class=&quot;flex w-full items-start&quot;]/div[@class=&quot;flex-1 px-2 pb-2&quot;]/main[@class=&quot;saved-feed&quot;]/main[@class=&quot;justify-center items-center&quot;]/div[@class=&quot;flex flex-col justify-center relative&quot;]/div[@class=&quot;max-w-full max-h-full&quot;]/div[@class=&quot;relative h-[300px] max-w-full max-h-full overflow-auto&quot;]/div[@class=&quot;absolute left-0 bottom-0 right-0 p-2 md:p-6&quot;]/div[1]/div[@class=&quot;md:mt-4 grid gap-2 md:gap-4 items-end md:items-center grid-cols-1 md:grid-cols-[1fr_2fr_1fr]&quot;]/div[@class=&quot;relative md:w-full md:h-full flex items-center p-2 rounded-[10px] overflow-hidden&quot;]/div[@class=&quot;relative h-full flex items-center justify-between gap-4&quot;]/div[@class=&quot;flex-1&quot;]/p[@class=&quot;!text-sm md:!text-base break-all !text-white/70 typography_LUXcC variant-subtitle_+fl6g font-weight-normal_aKbW-&quot;]</value>
      <webElementGuid>bc45e5e3-b326-4037-b0ff-a81f9bc401dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wolfden']/div[2]/div[2]/main/main/div/div/div/div[2]/div/div[2]/div/div[2]/div/p[2]</value>
      <webElementGuid>a887ec83-07a7-4376-8b7a-2fba8b43130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/following::p[14]</value>
      <webElementGuid>a00e50b8-7021-446d-860c-65c11b1f44da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/following::p[15]</value>
      <webElementGuid>9a598955-7658-4dc2-b3e8-5c40cedea236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/preceding::p[6]</value>
      <webElementGuid>e41135a2-b8d2-4449-8a1a-469e12c226ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Howls'])[1]/preceding::p[6]</value>
      <webElementGuid>df0e8979-3717-4551-88dc-1a9c2651d65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='@nguyenqhuy753101']/parent::*</value>
      <webElementGuid>007e8909-d530-4201-b168-8eb3d1bebf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>e533a791-7929-4b47-b03e-6075861696dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
            @nguyenqhuy753101
          ' or . = '
            @nguyenqhuy753101
          ')]</value>
      <webElementGuid>0eaf6ff2-0acc-4025-a07f-50429ed57760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
