<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>invalidUsernameOrPassword</name>
   <tag></tag>
   <elementGuidId>9a678a77-5b9d-40e7-9f68-02b28536acec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/span/div/div/div/div/div/small</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>small.inline-block.text-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Invalid username or password.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>403eb565-627a-4ff7-9ee2-f73ae0fcc33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-block text-xs</value>
      <webElementGuid>39dcd1d6-bcdd-4d0c-b1e3-6683f0366f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid username or password.</value>
      <webElementGuid>ad757c57-9a8f-4e57-a5c8-d7223cb52adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-black w-full h-screen relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;vue-notification-group&quot;]/span[1]/div[@class=&quot;vue-notification-wrapper&quot;]/div[@class=&quot;toastification bg-error&quot;]/div[@class=&quot;flex items-center gap-4&quot;]/div[@class=&quot;flex items-start flex-grow&quot;]/div[@class=&quot;flex flex-col gap-1&quot;]/small[@class=&quot;inline-block text-xs&quot;]</value>
      <webElementGuid>57c06537-94c8-4615-b69a-2f16cc257cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/span/div/div/div/div/div/small</value>
      <webElementGuid>204a6db2-d84d-466a-b23d-fb445b1335ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/following::small[1]</value>
      <webElementGuid>53720a98-bab6-49c2-bf11-4a33ea5b7a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::small[1]</value>
      <webElementGuid>4e4c2e67-74b4-4873-8f73-74e2072dc438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid username or password.']/parent::*</value>
      <webElementGuid>0e2a9d47-92bb-4476-877d-f26bef74303d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small</value>
      <webElementGuid>15257d59-eb64-4b49-98a2-6c3d63e2ccb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Invalid username or password.' or . = 'Invalid username or password.')]</value>
      <webElementGuid>6b0e5a7b-23a5-4191-91cb-4607b3e67a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
