<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordInput</name>
   <tag></tag>
   <elementGuidId>7aa9da02-878d-4670-9c3e-27bf232073f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Password must be 6 characters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a057619-11c1-495b-a1e3-e0e0e40931c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password must be 6 characters</value>
      <webElementGuid>fb6308b2-29ff-4afd-9b67-ddb0a595ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8b04bfc2-7d70-4cc7-9d3b-729643bf9c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full</value>
      <webElementGuid>d714f325-4a3a-4fbe-af55-9e8cc4d78e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-black w-full h-screen relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;w-full h-full relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;relative w-full h-full flex justify-center p-4&quot;]/div[@class=&quot;relative md:w-[600px] sm:w-[500px] w-full mx-auto flex flex-col items-center justify-center -top-16&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full bg-normal-600 p-4 sm:p-8 bg-grey-100 rounded-[40px] shadow-md border-4 border-solid border-normal-500&quot;]/form[@class=&quot;w-full flex flex-col items-center justify-center gap-6&quot;]/div[@class=&quot;flex flex-col gap-1 w-full&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full&quot;]</value>
      <webElementGuid>86ea801d-cf0e-4734-90a6-39ce76c0a5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>34984b13-7f9f-4b80-84d1-a2ee5231f0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/div[2]/form/div[2]/div/input</value>
      <webElementGuid>ffd2265b-2f80-4b0b-81eb-c451ff846cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>6525729d-f1bc-4403-bded-97e6021f531c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password must be 6 characters' and @type = 'password']</value>
      <webElementGuid>fa04e74e-a720-4cbd-8a52-86a6b9394021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
