<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>usernameInput</name>
   <tag></tag>
   <elementGuidId>59fe5d48-808d-42ab-acaf-8fdf440e5276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Profile name (not email address)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2e5b685-5568-445d-9191-fee691a7d1f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Profile name (not email address)</value>
      <webElementGuid>e5ec91b8-b9e8-45ec-8f3b-0fd91453f928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7609132-3f54-4665-a1aa-da90331cb89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full pl-3 pr-3</value>
      <webElementGuid>05526825-fc0b-4e33-9f05-63f1c3a21e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-black w-full h-screen relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;w-full h-full relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;relative w-full h-full flex justify-center p-4&quot;]/div[@class=&quot;relative md:w-[600px] sm:w-[500px] w-full mx-auto flex flex-col items-center justify-center -top-16&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full bg-normal-600 p-4 sm:p-8 bg-grey-100 rounded-[40px] shadow-md border-4 border-solid border-normal-500&quot;]/form[@class=&quot;w-full flex flex-col items-center justify-center gap-6&quot;]/div[@class=&quot;flex flex-col gap-1 w-full&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full pl-3 pr-3&quot;]</value>
      <webElementGuid>84c0064b-da21-44c3-8f33-61338e0a6880</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>3a9de73a-1c68-427c-aaf8-dbf29b63922b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>516bf9e2-c107-4df7-8490-b4136746479a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>92e696a9-1fcb-4f0d-a327-6590ad335158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Profile name (not email address)' and @type = 'text']</value>
      <webElementGuid>f0b3371b-f61e-409b-bf54-e7023c6c3a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
