<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>authorizeInput</name>
   <tag></tag>
   <elementGuidId>bada91a3-0191-464b-99a8-2f0d1387e892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c590e06-684b-40a1-b742-bc4139462544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>cfa0338d-6043-4267-b1bf-ff6cbda3dc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0bdc8fb6-037c-4506-8e8a-74bb2ef7e3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full</value>
      <webElementGuid>2621f677-3a9c-4d46-a521-e0813103619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-black w-full h-screen relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;w-full h-full relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;relative z-30 w-full h-full flex justify-center&quot;]/div[@class=&quot;relative w-[344px] mx-auto flex flex-col items-center justify-center -top-16&quot;]/div[@class=&quot;pt-4 w-full&quot;]/form[@class=&quot;flex flex-col items-center justify-center gap-6&quot;]/div[@class=&quot;flex flex-col gap-1 w-full&quot;]/div[@class=&quot;relative w-full&quot;]/input[@class=&quot;border border-solid border-normal-500 bg-normal-600 text-white rounded py-[9px] pr-10 pl-9 text-sm w-full&quot;]</value>
      <webElementGuid>bc663efc-27fe-43eb-a2b2-621518d9c31b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>e2b324fe-4565-4629-a859-da7bcd4d5ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>eb231e4c-7614-4bf4-92e9-434436496791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>902638c3-5753-4288-b972-5c4ee3b1a440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>93c0a757-9c9a-47d7-ab98-56f34eebca20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
