<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitBtn</name>
   <tag></tag>
   <elementGuidId>25053418-0bc8-4e8b-81b3-57ab1ac3387b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mt-2.button.block.semibold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a79dcb0c-f299-40c7-8a26-9e53c83c7a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa775e13-7853-41ab-8cbe-3549d94673d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>block</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bd0176bf-5310-42cf-8c9c-8c9d22753f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fontweight</name>
      <type>Main</type>
      <value>semibold</value>
      <webElementGuid>f1a0cc35-ea23-4dbd-922c-1a2c4ec3ccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-2 button block semibold</value>
      <webElementGuid>ae17ff80-5982-476d-b3c4-2d6a005587a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Submit
        </value>
      <webElementGuid>f4a0d20d-9037-4145-9042-4be9a284d2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-black w-full h-screen relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;w-full h-full relative flex flex-col items-center justify-center&quot;]/div[@class=&quot;relative z-30 w-full h-full flex justify-center&quot;]/div[@class=&quot;relative w-[344px] mx-auto flex flex-col items-center justify-center -top-16&quot;]/div[@class=&quot;pt-4 w-full&quot;]/form[@class=&quot;flex flex-col items-center justify-center gap-6&quot;]/button[@class=&quot;mt-2 button block semibold&quot;]</value>
      <webElementGuid>dde79ec0-bc1b-407b-8ff4-1aec51d9e9a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>ec4e0842-36d1-42f4-8eec-da43c55bd5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/div/div/div/form/button</value>
      <webElementGuid>0ba6b495-5e70-4bd9-918c-869255c107fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorize'])[1]/following::button[1]</value>
      <webElementGuid>cc3f0154-8bbd-432a-ae6d-55c37a8d6991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>450e99f4-8343-47f8-b822-b71433614d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8d007c5d-622f-4eb8-8b94-5cb8cdcb5cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
          Submit
        ' or . = '
          Submit
        ')]</value>
      <webElementGuid>68331789-c8f6-4768-9606-79407bcabf84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
